apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tp-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tp-k8s-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/app
            - name: PORT
              value: "3000"