apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: tp-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://mongodb:27017
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: admin